freebsd_instance:
  cpu: 4
  memory: 8G

task:
  matrix:
    # No motivation to backport module to 13.5-RELEASE
    #- name: releases/amd64/13.5-RELEASE
    #  freebsd_instance:
    #    image_family: freebsd-13-5
    - name: releases/amd64/14.3-RELEASE
      freebsd_instance:
        image_family: freebsd-14-3
    - name: releases/amd64/15.0-RC2
      freebsd_instance:
        image_family: freebsd-15-0-amd64-ufs
  stateful: false
  env:
    WD: /tmp/wd
    PATH: /usr/local/sbin:${PATH}
    ARCHIVES_BASE: https://download.freebsd.org/${CIRRUS_TASK_NAME}
  build_setup_script:
    - mkdir ${WD}
    - cd ${WD} && fetch -q ${ARCHIVES_BASE}/kernel.txz
    - tar xf ${WD}/kernel.txz -C / && rm ${WD}/kernel.txz
    - cd ${WD} && fetch -q ${ARCHIVES_BASE}/kernel-dbg.txz
    - tar xf ${WD}/kernel-dbg.txz -C / && rm ${WD}/kernel-dbg.txz
    - cd ${WD} && fetch -q ${ARCHIVES_BASE}/src.txz
    - tar xf ${WD}/src.txz -C / && rm ${WD}/src.txz
    # Check for WITNESS and INVARIANTS and add args for make when present.
    - sysctl -n kern.conftxt | awk '
        /^options\t(WITNESS|INVARIANTS)$/ { opts = opts " -D" $2 }
        END { print "DEBUG_FLAGS=-g -O0" opts }
      ' | tee -a ${CIRRUS_ENV} >&2
  build_script:
    - make DEBUG_FLAGS="${DEBUG_FLAGS}" -j${CIRRUS_CPU}
    - make DEBUG_FLAGS="${DEBUG_FLAGS}" install
  manlint_script:
    - make manlint
  messages_background_script:
    - tail -F -n +1 /var/log/messages
  load_script:
    - gnbd load
    - sysctl kern.geom.nbd.debug=1
    - sysctl kern.ipc.tls.enable=1
    # Avoid IP queue drops.
    - sysctl net.inet.ip.intr_queue_maxlen=`sysctl -n net.isr.maxqlimit`
  ca_info_file:
    path: ${WD}/ca.info
    from_contents: |
      cn = testing nbd client
      ca
      cert_signing_key
  server_info_file:
    path: ${WD}/server.info
    from_contents: |
      organization = testing nbd client
      cn = localhost
      tls_www_server
      encryption_key
      signing_key
  client_info_file:
    path: ${WD}/client.info
    from_contents: |
      country = US
      state = Florida
      locality = Orlando
      organization = testing nbd client
      cn = localhost
      tls_www_client
      encryption_key
      signing_key
  test_setup_script:
    - pkg install -y
      isal-kmod
      gnutls
      nbdkit
    # Certificate Authority
    - certtool --generate-privkey > ${WD}/ca-key.pem
    - certtool --generate-self-signed
      --load-privkey ${WD}/ca-key.pem
      --template ${WD}/ca.info
      --outfile ${WD}/ca-cert.pem
    # Server
    - certtool --generate-privkey > ${WD}/server-key.pem
    - certtool --generate-certificate
      --load-ca-certificate ${WD}/ca-cert.pem
      --load-ca-privkey ${WD}/ca-key.pem
      --load-privkey ${WD}/server-key.pem
      --template ${WD}/server.info
      --outfile ${WD}/server-cert.pem
    # Client
    - certtool --generate-privkey > ${WD}/client-key.pem
    - certtool --generate-certificate
      --load-ca-certificate ${WD}/ca-cert.pem
      --load-ca-privkey ${WD}/ca-key.pem
      --load-privkey ${WD}/client-key.pem
      --template ${WD}/client.info
      --outfile ${WD}/client-cert.pem
    # Intelligent Storage Acceleration Library - faster ktls crypto routines
    - kldload isal
  test_server_background_script:
    - nbdkit
      --no-fork
      --threads ${CIRRUS_CPU}
      --tls-certificates ${WD}
      memory 4G
  test_list_notls_script:
    - gnbd exports localhost
  test_connect_notls_script:
    - gnbd connect localhost
      | xargs -I @ echo NBD=@ | tee -a ${CIRRUS_ENV} >&2
  test_notls_script:
    # Test with 1 connection.
    - gnbd status >&2
    - gnbd status | egrep -q "^${NBD}(\s+)"
    - gnbd list >&2
    - gnbd list ${NBD} | egrep -q "^Geom name:(\s+)${NBD}$"
    - gnbd list ${NBD} | egrep -q "^TLS:(\s+)no$"
    - gnbd list ${NBD} | egrep -q "^Connections:(\s+)1$"
    - diskinfo -twic ${NBD} >&2
    # Test with 4 conections (scaling up).
    - gnbd scale -c 4 ${NBD}
    - gnbd list ${NBD} | egrep -q "^Connections:(\s+)4$"
    - diskinfo -twic ${NBD} >&2
    # Test with 2 connections (scaling down).
    - gnbd scale -c 2 ${NBD}
    # Scaling down happens asynchronously, connections need time to close.
    - sleep 1
    - gnbd list ${NBD} | egrep -q "^Connections:(\s+)2$"
    - diskinfo -twic ${NBD} >&2
    # Test the lldb script.
    - lldb -b -o "script dofile 'gnbd.lua'" -c /dev/mem /boot/kernel/kernel
    # Clean up.
    - gnbd disconnect ${NBD}
    # Unset the NBD variable in the env.
    - sed -i '' -e '/^NBD=/d' ${CIRRUS_ENV}
  test_list_tls_script:
    - gnbd exports
      -A ${WD}/ca-cert.pem
      -C ${WD}/client-cert.pem
      -K ${WD}/client-key.pem
      localhost
  test_connect_tls_script:
    - gnbd connect
      -A ${WD}/ca-cert.pem
      -C ${WD}/client-cert.pem
      -K ${WD}/client-key.pem
      localhost
      | xargs -I @ echo NBD=@ | tee -a ${CIRRUS_ENV} >&2
  test_tls_script:
    # Test with 1 connection.
    - gnbd status >&2
    - gnbd status | egrep -q "^${NBD}(\s+)"
    - gnbd list >&2
    - gnbd list ${NBD} | egrep -q "^Geom name:(\s+)${NBD}$"
    - gnbd list ${NBD} | egrep -q "^TLS:(\s+)yes$"
    - gnbd list ${NBD} | egrep -q "^Connections:(\s+)1$"
    - diskinfo -twic ${NBD} >&2
    # Test with 4 conections (scaling up).
    - gnbd scale -c 4
      -A ${WD}/ca-cert.pem
      -C ${WD}/client-cert.pem
      -K ${WD}/client-key.pem
      ${NBD}
    - gnbd list ${NBD} | egrep -q "^Connections:(\s+)4$"
    - diskinfo -twic ${NBD} >&2
    # Test with 2 connections (scaling down).
    - gnbd scale -c 2
      -A ${WD}/ca-cert.pem
      -C ${WD}/client-cert.pem
      -K ${WD}/client-key.pem
      ${NBD}
    # Scaling down happens asynchronously, connections need time to close.
    - sleep 1
    - gnbd list ${NBD} | egrep -q "^Connections:(\s+)2$"
    - diskinfo -twic ${NBD} >&2
    # Test the lldb script.
    - lldb -b -o "script dofile 'gnbd.lua'" -c /dev/mem /boot/kernel/kernel
    # Clean up.
    - gnbd disconnect ${NBD}
    # Unset the NBD variable in the env.
    - sed -i '' -e '/^NBD=/d' ${CIRRUS_ENV}
  trace_setup_script:
    - pkg install -y fio flamegraph
    - mkdir traces
    - mount -t tmpfs tmp ./traces
    - kldload dtraceall
    # GCE images have ifconfig_DEFAULT="SYNCDHCP mtu 1460" which makes lo0 pass
    # loopback traffic through JUMBOP mbufs with less than half the space used.
    # This means socket buffers run out of space with nowhere near enough actual
    # data present, and generally tanks performance.  Restore the default MTU
    # only while gathering profiles so we have coverage for regressions.
    - ifconfig lo0 mtu 16384
  trace_connect_notls_script:
    - gnbd connect -c 4 localhost
      | xargs -I @ echo NBD=@ | tee -a ${CIRRUS_ENV} >&2
  trace_notls_script:
    - dtrace -x stackframes=100
      -c "fio ci.fio --iodepth=32 --bs=4k --filename=/dev/${NBD}
          --output=./traces/notls-32-4k.fio.json --output-format=json+"
      -n 'profile-197 /arg0/ { @[stack()] = count(); }'
      -o ./traces/dtrace.stacks
    - stackcollapse.pl ./traces/dtrace.stacks
      | grep -v sched_idletd > ./traces/notls-32-4k.collapsedstack.txt
    - flamegraph.pl ./traces/notls-32-4k.collapsedstack.txt
      > ./traces/notls-32-4k.svg
    - rm ./traces/dtrace.stacks
    - dtrace -x stackframes=100
      -c "fio ci.fio --iodepth=4 --bs=1m --filename=/dev/${NBD}
          --output=./traces/notls-4-1m.fio.json --output-format=json+"
      -n 'profile-197 /arg0/ { @[stack()] = count(); }'
      -o ./traces/dtrace.stacks
    - stackcollapse.pl ./traces/dtrace.stacks
      | grep -v sched_idletd > ./traces/notls-4-1m.collapsedstack.txt
    - flamegraph.pl ./traces/notls-4-1m.collapsedstack.txt
      > ./traces/notls-4-1m.svg
    - rm ./traces/dtrace.stacks
    - gnbd disconnect ${NBD}
    - sed -i '' -e '/^NBD=/d' ${CIRRUS_ENV}
  trace_connect_tls_script:
    - gnbd connect -c 4
      -A ${WD}/ca-cert.pem
      -C ${WD}/client-cert.pem
      -K ${WD}/client-key.pem
      localhost
      | xargs -I @ echo NBD=@ | tee -a ${CIRRUS_ENV} >&2
  trace_tls_script:
    - dtrace -x stackframes=100
      -c "fio ci.fio --iodepth=32 --bs=4k --filename=/dev/${NBD}
          --output=./traces/tls-32-4k.fio.json --output-format=json+"
      -n 'profile-197 /arg0/ { @[stack()] = count(); }'
      -o ./traces/dtrace.stacks
    - stackcollapse.pl ./traces/dtrace.stacks
      | grep -v sched_idletd > ./traces/tls-32-4k.collapsedstack.txt
    - flamegraph.pl ./traces/tls-32-4k.collapsedstack.txt
      > ./traces/tls-32-4k.svg
    - rm ./traces/dtrace.stacks
    - dtrace -x stackframes=100
      -c "fio ci.fio --iodepth=4 --bs=1m --filename=/dev/${NBD}
          --output=./traces/tls-4-1m.fio.json --output-format=json+"
      -n 'profile-197 /arg0/ { @[stack()] = count(); }'
      -o ./traces/dtrace.stacks
    - stackcollapse.pl ./traces/dtrace.stacks
      | grep -v sched_idletd > ./traces/tls-4-1m.collapsedstack.txt
    - flamegraph.pl ./traces/tls-4-1m.collapsedstack.txt
      > ./traces/tls-4-1m.svg
    - rm ./traces/dtrace.stacks
    - gnbd disconnect ${NBD}
    - sed -i '' -e '/^NBD=/d' ${CIRRUS_ENV}
  fio_artifacts:
    path: "./traces/*.fio.json"
  trace_artifacts:
    path: "./traces/*.collapsedstack.txt"
  svg_artifacts:
    path: "./traces/*.svg"
  debug_script:
    - dmesg >&2
    - vmstat -z >&2
    - vmstat -m >&2
