freebsd_instance:
  cpu: 4
  memory: 8G

task:
  matrix:
    # No motivation to backport module to 13.5-RELEASE
    #- freebsd_instance:
    #    image_family: freebsd-13-5
    #  env:
    #    ARCHIVES_PATH: releases/amd64/13.5-RELEASE
    - freebsd_instance:
        image_family: freebsd-14-2
      env:
        ARCHIVES_PATH: releases/amd64/14.2-RELEASE
    #- freebsd_instance:
    #    image_family: freebsd-15-0-snap
    #  env:
    #    ARCHIVES_PATH: snapshots/amd64/15.0-CURRENT
  name: ${ARCHIVES_PATH}
  stateful: false
  env:
    WD: /tmp/wd
    PATH: /usr/local/sbin:${PATH}
    ARCHIVES_BASE: https://download.freebsd.org/${ARCHIVES_PATH}
  build_setup_script:
    - mount >&2
    - mkdir ${WD}
    - cd ${WD} && fetch -q ${ARCHIVES_BASE}/kernel-dbg.txz
    - tar xf ${WD}/kernel-dbg.txz -C / && rm ${WD}/kernel-dbg.txz
    - cd ${WD} && fetch -q ${ARCHIVES_BASE}/src.txz
    - tar xf ${WD}/src.txz -C / && rm ${WD}/src.txz
    # Check for WITNESS and INVARIANTS and add args for make when present.
    - sysctl -n kern.conftxt
      | sed -nE '/^options\t(WITNESS|INVARIANTS)$/s/options\t/-D/p'
      | xargs -I @ -L 2 echo 'DEBUG_ARGS=DEBUG_FLAGS="-g -O0 @"'
      | tee -a ${CIRRUS_ENV} >&2
  build_script:
    # eval needed for proper variable expansion. Cirrus counts it as an empty
    # arg when empty, but we want no args from it when empty.
    - eval make ${DEBUG_ARGS} -j${CIRRUS_CPU}
    - eval make ${DEBUG_ARGS} install
  messages_background_script:
    - tail -F -n +1 /var/log/messages
  top_background_script:
    - top -SHIPnz -s 60 -d infinity
  netstat_background_script:
    - netstat -w 60 -I lo0 -dnh
  load_script:
    - gnbd load
    - sysctl kern.geom.nbd.debug=2
    - sysctl kern.ipc.tls.enable=1
  lldb_background_script:
    - while sleep 60; do
        echo;
        netstat -Q;
        gnbd list || true;
        sysctl kern.geom.nbd || true;
        sysctl kern.ipc.tls || true;
        sysctl dev.isal.0.stats || true
        lldb -b -o "script -l lua -- dofile 'gnbd.lua'"
          -c /dev/mem /boot/kernel/kernel;
      done
  ca_info_file:
    path: ${WD}/ca.info
    from_contents: |
      cn = testing nbd client
      ca
      cert_signing_key
  server_info_file:
    path: ${WD}/server.info
    from_contents: |
      organization = testing nbd client
      cn = localhost
      tls_www_server
      encryption_key
      signing_key
  client_info_file:
    path: ${WD}/client.info
    from_contents: |
      country = US
      state = Florida
      locality = Orlando
      organization = testing nbd client
      cn = localhost
      tls_www_client
      encryption_key
      signing_key
  test_setup_script:
    - pkg install -y
      isal-kmod
      gnutls
      nbdkit
    # Certificate Authority
    - certtool --generate-privkey > ${WD}/ca-key.pem
    - certtool --generate-self-signed
      --load-privkey ${WD}/ca-key.pem
      --template ${WD}/ca.info
      --outfile ${WD}/ca-cert.pem
    # Server
    - certtool --generate-privkey > ${WD}/server-key.pem
    - certtool --generate-certificate
      --load-ca-certificate ${WD}/ca-cert.pem
      --load-ca-privkey ${WD}/ca-key.pem
      --load-privkey ${WD}/server-key.pem
      --template ${WD}/server.info
      --outfile ${WD}/server-cert.pem
    # Client
    - certtool --generate-privkey > ${WD}/client-key.pem
    - certtool --generate-certificate
      --load-ca-certificate ${WD}/ca-cert.pem
      --load-ca-privkey ${WD}/ca-key.pem
      --load-privkey ${WD}/client-key.pem
      --template ${WD}/client.info
      --outfile ${WD}/client-cert.pem
    # Intelligent Storage Acceleration Library - faster ktls crypto routines
    - kldload isal
  test_server_background_script:
    - nbdkit
      --no-fork
      --threads ${CIRRUS_CPU}
      --tls-certificates ${WD}
      memory 4G
  trace_setup_script:
    - pkg install -y fio flamegraph
    - mkdir traces
    - mount -t tmpfs tmp ./traces
    - kldload dtraceall
  debug1_script:
    - df -h >&2
    - swapinfo -h >&2
  trace_connect_notls_script:
    - gnbd connect localhost
      | xargs -I @ echo NBD=@ | tee -a ${CIRRUS_ENV} >&2
  trace_notls_32_4k_script:
    - dtrace -x stackframes=100
      -c "fio ci.fio --iodepth=32 --bs=4k --filename=/dev/${NBD}
          --output=./traces/notls-32-4k.fio.json --output-format=json+"
      -n 'profile-197 /arg0/ { @[stack()] = count(); }'
      -o ./traces/dtrace.stacks
    - stackcollapse.pl ./traces/dtrace.stacks
      | grep -v sched_idletd > ./traces/notls-32-4k.collapsedstack.txt
    - flamegraph.pl ./traces/notls-32-4k.collapsedstack.txt
      > ./traces/notls-32-4k.svg
    - rm ./traces/dtrace.stacks
  debug1b_script:
    - df -h >&2
    - swapinfo -h >&2
  trace_notls_4_1m_script:
    - dtrace -x stackframes=100
      -c "fio ci.fio --iodepth=4 --bs=1m --filename=/dev/${NBD}
          --output=./traces/notls-4-1m.fio.json --output-format=json+"
      -n 'profile-197 /arg0/ { @[stack()] = count(); }'
      -o ./traces/dtrace.stacks
    - stackcollapse.pl ./traces/dtrace.stacks
      | grep -v sched_idletd > ./traces/notls-4-1m.collapsedstack.txt
    - flamegraph.pl ./traces/notls-4-1m.collapsedstack.txt
      > ./traces/notls-4-1m.svg
    - rm ./traces/dtrace.stacks
  debug_1c_script:
    - df -h >&2
    - swapinfo -h >&2
  trace_disconnect_notls_script:
    - gnbd disconnect ${NBD}
    - sed -i '' -e '/^NBD=/d' ${CIRRUS_ENV}
  debug2_script:
    - df -h >&2
    - swapinfo -h >&2
  trace_connect_tls_script:
    - gnbd connect
      -A ${WD}/ca-cert.pem
      -C ${WD}/client-cert.pem
      -K ${WD}/client-key.pem
      localhost
      | xargs -I @ echo NBD=@ | tee -a ${CIRRUS_ENV} >&2
  trace_tls_32_4k_script:
    - dtrace -x stackframes=100
      -c "fio ci.fio --iodepth=32 --bs=4k --filename=/dev/${NBD}
          --output=./traces/tls-32-4k.fio.json --output-format=json+"
      -n 'profile-197 /arg0/ { @[stack()] = count(); }'
      -o ./traces/dtrace.stacks
    - stackcollapse.pl ./traces/dtrace.stacks
      | grep -v sched_idletd > ./traces/tls-32-4k.collapsedstack.txt
    - flamegraph.pl ./traces/tls-32-4k.collapsedstack.txt
      > ./traces/tls-32-4k.svg
    - rm ./traces/dtrace.stacks
  debug2b_script:
    - df -h >&2
    - swapinfo -h >&2
  trace_tls_4_1m_script:
    - dtrace -x stackframes=100
      -c "fio ci.fio --iodepth=4 --bs=1m --filename=/dev/${NBD}
          --output=./traces/tls-4-1m.fio.json --output-format=json+"
      -n 'profile-197 /arg0/ { @[stack()] = count(); }'
      -o ./traces/dtrace.stacks
    - stackcollapse.pl ./traces/dtrace.stacks
      | grep -v sched_idletd > ./traces/tls-4-1m.collapsedstack.txt
    - flamegraph.pl ./traces/tls-4-1m.collapsedstack.txt
      > ./traces/tls-4-1m.svg
    - rm ./traces/dtrace.stacks
  debug2c_script:
    - df -h >&2
    - swapinfo -h >&2
  trace_disconnect_tls_script:
    - gnbd disconnect ${NBD}
    - sed -i '' -e '/^NBD=/d' ${CIRRUS_ENV}
  fio_artifacts:
    path: "./traces/*.fio.json"
  trace_artifacts:
    path: "./traces/*.collapsedstack.txt"
  svg_artifacts:
    path: "./traces/*.svg"
  debug_script:
    - df -h >&2
    - swapinfo -h >&2
    - dmesg >&2
    - vmstat -z >&2
    - vmstat -m >&2
