.\" Copyright (c) 2025 Ryan Moeller
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd March 20, 2025
.Dt GNBD 8
.Os
.Sh NAME
.Nm gnbd
.Nd "control utility for the network block device GEOM class"
.Sh SYNOPSIS
To load the GEOM_ELI module at boot time, add the following line
to your
.Xr loader.conf 5 :
.Bd -literal -offset indent
geom_nbd_load="YES"
.Ed
.Pp
.No Usage of the Nm
utility:
.Pp
.Nm
.Cm connect
.Op Fl c Ar num
.Op Fl n Ar name
.Op Fl p Ar port
.Ar host
.Nm
.Cm connect
.Op Fl c Ar num
.Op Fl n Ar name
.Op Fl p Ar port
.Op Fl A Ar cacert
.Fl C Ar cert
.Fl K Ar key
.Ar host
.Nm
.Cm scale
.Fl c Ar num
.Ar prov
.Nm
.Cm scale
.Fl c Ar num
.Op Fl A Ar cacert
.Fl C Ar cert
.Fl K Ar key
.Ar prov
.Nm
.Cm disconnect
.Ar prov
.Nm
.Cm help
.Nm
.Cm list
.Op Fl a
.Op Ar prov ...
.Nm
.Cm status
.Op Fl ags
.Op Ar prov ...
.Nm
.Cm load
.Op Fl v
.Nm
.Cm unload
.Op Fl v
.Sh DESCRIPTION
The
.Nm
utility is used to configure network block device (NBD) GEOM providers.
.Pp
The following is a list of the most important features:
.Pp
.Bl -bullet -offset indent -compact
.It
Established connections are handed off to the kernel, allowing reroot onto
the network-backed devices.
.It
Supports using multiple connections to the NBD server to parallelize commands.
.It
Supports optional TLS encryption using
.Xr ktls 4 .
.It
It is fast - zero copies are performed where possible.
.El
.Pp
The first argument to
.Nm
indicates an action to be performed:
.Bl -tag -width ".Cm disconnect"
.It Cm connect
Connect to an NBD server.
The number of connections can be specified by
.Fl c ,
by default one connection is made.
If the name of an export is not given by
.Fl n ,
the default export is requested.
To make TLS connections, both a certificate and key must be given with
.Fl C
and
.Fl K ,
and a CA certificate for verifying certificates may optionally be
provided using
.Fl A ,
otherwise the default system root CAs are used.
.It Cm scale
Scale the number of connections for an existing device up or down to the number
specified by
.Fl c .
To scale up the connections for a device using TLS, the certificate and key must
be given with
.Fl C
and
.Fl K ,
and a CA certificate for verifying certificates may optionally be
provided using
.Fl A ,
otherwise the default system root CAs are used.
.It Cm disconnect
Disconnect and remove the given provider.
.It Cm help
See
.Xr geom 8 .
.It Cm list
See
.Xr geom 8 .
.It Cm load
See
.Xr geom 8 .
.It Cm unload
See
.Xr geom 8 .
.El
.Sh TLS
All TLS certificates and keys must be in PEM format.
TLS certificates may be a certificate chain to include intermediary certificates
in the chain of trust.
.Sh SYSCTL TUNABLES
The following
.Xr sysctl 8
tunables can be used to control the behavior of the
.Nm NBD
GEOM class.
The default value is shown next to each variable.
.Bl -tag -width indent
.It Va kern.geom.nbd.debug : No 0
Debug level of the
.Nm NBD
GEOM class.
This can be set to a number between 0 and 5 inclusive.
If set to 0, minimal debug information is printed.
If set to 5, the maximum amount of debug information is printed.
.It Va kern.geom.nbd.maxpayload : No 262144 Pq 256 kiB
Upper limit on the size in bytes of a single transfer over the network.
.Pp
Note: connections may also be limited by standard socket buffer limits.
.It Va kern.geom.nbd.sendspace : No 1572864 Pq 1536 kiB
Size of socket send buffer reservation per connection.
.Pp
Note: connections may also be limited by standard socket buffer limits.
.It Va kern.geom.nbd.recvspace : No 1572864 Pq 1536 kiB
Size of socket receive buffer reservation per connection.
.Pp
Note: connections may also be limited by standard socket buffer limits.
.It Va kern.geom.nbd.identfmt : No 0
Format of the GEOM::ident attribute.
.Pp
Setting to 0 uses the format "host:port/name".
Setting to 1 uses "name" if the export has a name, falling back to
"host:port/name" when the name is empty
.Pq default export .
Setting to 2 always uses "name", even if the name is empty.
.Pp
Formats 1 and 2 can be useful when the export names are serial numbers.
.El
.Sh EXIT STATUS
Exit status is 0 on success, and 1 if the command fails.
.Sh EXAMPLES
Connect to an NBD server with 4 connections:
.Bd -literal -offset indent
# gnbd connect -c 4 servername
nbd0
.Ed
.Pp
Connect to an NBD server using TLS with an internal CA and 2 connections:
.Bd -literal -offset indent
# gnbd connect -c 2 -A cacert.pem -C cert.pem -K key.pem servername
nbd1
.Ed
.Pp
Scale the second provider up to 8 connections:
.Bd -literal -offset indent
# gnbd scale -c 8 -A cacert.pem -C cert.pem -K key.pem servername
.Ed
.Pp
Disconnect the previous examples:
.Bd -literal -offset indent
# gnbd disconnect nbd0
# gnbd disconnect nbd1
.Ed
.Sh SEE ALSO
.Xr geom 4 ,
.Xr ktls 4 ,
.Xr loader.conf 5 ,
.Xr geom 8
.Sh AUTHORS
.An Ryan Moeller
